name: ornl CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  2xa30-2:
    runs-on: [self-hosted, Linux, X64]

    env:
      GH_JOBNAME: ${{matrix.jobname}}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [GCC12-MPI-CUDA-Real-Full]
    #            GCC12-MPI-NoMPI-CUDA-Real-Full,
    #            GCC12-MPI-NoMPI-CUDA-Real-Debug-Full,

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Configure
        run: test/test_automation/ci/run_step.sh configure

      - name: Build
        run: test/test_automation/ci/run_step.sh build

      - name: Test
        run: test/test_automation/ci/run_step.sh test
